spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 074d9b0b207d7c
    password: b20b1e558caac0
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: project
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: project
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    table: project_schema_version
    baseline-version: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

vars:
  security:
    enable: true

server:
  port: 8090

token:
  ttl: 3600000
  secret: "https://www.youtube.com/watch?v=VBUMYOYJISc"

admin:
  username: admin
  email: admin@admin.com
  password: admin



